Repository Archi7echs-Team/MVP, pull requests merged in 2025-04, with the labels that each got.

#40 CI
  .github/workflows/ci.yml
  README.md
  app/vite.config.ts
  backend/pom.xml
Labels: Front-end, Back-end

#42 Front-end: aggiunta funzionalità
  app/src/lib/components/Bar.svelte
  app/src/lib/components/BarPane.svelte
  app/src/lib/components/Chart.svelte
  app/src/lib/components/Color.svelte
  app/src/lib/components/Export.svelte
  app/src/lib/components/SettingsPane.svelte
  app/src/lib/index.svelte.ts
  app/src/test/Color.svelte.test.ts
  app/src/test/SettingsPane.svelte.test.ts
Labels: Front-end

#43 Api integration
  .gitignore
  app/src/lib/components/App.svelte
  app/src/lib/components/Bar.svelte
  app/src/lib/components/BarPane.svelte
  app/src/lib/components/CameraSettings.svelte
  app/src/lib/components/Chart.svelte
  app/src/lib/components/Color.svelte
  app/src/lib/components/DataFilter.svelte
  app/src/lib/components/DataSource.svelte
  app/src/lib/components/SettingsPane.svelte
  app/src/lib/data.svelte.ts
  app/src/lib/index.svelte.ts
  app/src/test/App.svelte.test.ts
  app/src/test/CameraSettings.svelte.test.ts
  app/src/test/Chart.svelte.test.ts
  app/src/test/Color.svelte.test.ts
  app/src/test/DataFilter.svelte.test.ts
  app/vite.config.ts
  backend/init-data.sql
  backend/src/main/java/com/dataviz/backend/controller/CoordinateController.java
  backend/src/main/java/com/dataviz/backend/controller/ExternalDataController.java
  backend/src/main/java/com/dataviz/backend/controller/UploadController.java
  backend/src/main/java/com/dataviz/backend/model/CoordinateEntity.java
  backend/src/test/java/com/dataviz/backend/controller/CoordinateControllerTest.java
  backend/src/test/java/com/dataviz/backend/controller/ExternallDataControllerTest.java
  backend/src/test/java/com/dataviz/backend/controller/UploadControllerTest.java
Labels: Front-end

#48 Frontend: continuazione test
  app/.gitignore
  app/package-lock.json
  app/package.json
  app/playwright.config.ts
  app/src/lib/components/Bar.svelte
  app/src/lib/components/BarPane.svelte
  app/src/lib/components/CameraSettings.svelte
  app/src/lib/components/Chart.svelte
  app/src/lib/components/Export.svelte
  app/src/lib/index.svelte.ts
  app/src/test/Bar.svelte.test.ts
  app/src/test/BarPane.svelte.test.ts
  app/src/test/CameraSettings.svelte.test.ts
  app/src/test/Export.svelte.test.ts
  app/src/test/index.svelte.test.ts
  app/tests/example.spec.ts
  app/vite.config.ts
Labels: Front-end

#50 Front-end: test e fix
  app/playwright.config.ts
  app/playwright_test/example.spec.ts
  app/src/lib/components/App.svelte
  app/src/lib/components/Bar.svelte
  app/src/lib/components/BarPane.svelte
  app/src/lib/components/CameraSettings.svelte
  app/src/lib/components/Chart.svelte
  app/src/lib/components/DataFilter.svelte
  app/src/lib/components/DataSource.svelte
  app/src/lib/components/SettingsPane.svelte
  app/src/lib/data.svelte.ts
  app/src/lib/index.svelte.ts
  app/src/test/+page.svelte.test.ts
  app/src/test/App.svelte.test.ts
  app/src/test/Bar.svelte.test.ts
  app/src/test/BarPane.svelte.test.ts
  app/src/test/CameraSettings.svelte.test.ts
  app/src/test/Chart.svelte.test.ts
  app/src/test/Color.svelte.test.ts
  app/src/test/DataSource.svelte.test.ts
  app/src/test/SettingsPane.svelte.test.ts
  app/src/test/data.svelte.test.ts
  app/src/test/index.svelte.test.ts
Labels: Front-end

#52 Docker for deploy
  README.md
  app/Dockerfile
  docker-compose.yml
Labels: Front-end, Back-end

#55 Fix tests docker
  app/package-lock.json
  app/src/lib/data.svelte.ts
  app/src/test/data.svelte.test.ts
  backend/pom.xml
  backend/src/main/resources/application.properties
  docker-compose.yml
Labels: Front-end, Back-end

#59 Fix index.svelt sortedData
  app/src/lib/index.svelte.ts
Labels: Front-end

#62 added fixes
  backend/src/main/java/com/dataviz/backend/adapter/out/external/ExternalAPIAdapter.java
  backend/src/main/java/com/dataviz/backend/adapter/out/persistence/CoordinateJpaAdapter.java
  backend/src/main/java/com/dataviz/backend/domain/port/out/CoordinateLoaderPort.java
  backend/src/main/java/com/dataviz/backend/domain/port/out/ExternalDataPort.java
  backend/src/main/java/com/dataviz/backend/service/impl/DefaultCoordinateService.java
  backend/src/main/java/com/dataviz/backend/service/impl/DefaultExternalDataService.java
  backend/src/test/java/com/dataviz/backend/service/impl/DefaultExternalDataServiceTest.java
  backend/src/test/java/com/dataviz/backend/service/impl/ExtenalAPIAdapterTest.java
Labels: Back-end
